name: NexusFallback
main: gg.projecteden.nexus.fallback.NexusFallback
author: GriffinCodes
version: ${project.version}
api-version: 1.17
load: STARTUP
loadbefore:
  - Nexus
depend:
  - WorldGuard
  - WorldEdit
